### ISSUE TITLE
Support Github SCM operations retrieve and publish with Persist, Deploy, Detect, Remediate Actions

### ISSUE THREAD

**Issue by rohitthakur2590** [redhat-cop/network.bgp#30]
Support Github SCM operations with in Persist and Deploy Actions
##### SUMMARY

- Enable network.bgp to fetch facts and save the host_vars to github repositories. 
- Enable network.bgp to retrieve host_vars from github repository and deploy changes.

##### ISSUE TYPE
- Feature Idea

###### Default data store persist operation
```yaml
---
- hosts: rtr1
  gather_facts: true
  tasks:
    - name: Network BGP Manager
      ansible.builtin.include_role:
        name: network.bgp.run
      vars:
        action: persist
        ansible_network_os: cisco.ios.ios
```
###### SCM  driven Operation
```yaml
---
- hosts: rtr1
  gather_facts: true
  tasks:
    - name: Network BGP Manager
      ansible.builtin.include_role:
        name: network.bgp.run
      vars:
        action: persist
        ansible_network_os: cisco.ios.ios
        data_store:  
            scm:
              origin:
                 url: https://github.com/rohitthakur2590/network_validated_content_automation.git
                 token:  "{{ GH_PAT }}"
                 user:
                    name: rohitthakur2590
                    email: rohitthakur2590@outlook.com
```
###### Local data store driven persist operation
```yaml
---
- hosts: rtr1
  gather_facts: true
  tasks:
    - name: Network BGP Manager
      ansible.builtin.include_role:
        name: network.bgp.run
      vars:
        action: persist
        ansible_network_os: cisco.ios.ios
        data_store:
          local: "~/backup/network"
```
###### SCM driven deploy operation
```yaml
---
- hosts: rtr1
  gather_facts: true
  tasks:
    - name: Network BGP Manager
      ansible.builtin.include_role:
        name: network.bgp.run
      vars:
        action: deploy
        ansible_network_os: cisco.ios.ios
        resources:
          - 'all'
        data_store:  
          scm:
              origin:
                  url: https://github.com/rohitthakur2590/network_validated_content_automation.git
```
